### PR TITLE
fix(Component): remove sha hash from container image url

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-1092

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
looks good @sahil143 , can we add/update a test here for this check

**Comment by sahil143** [comment]
> looks good @sahil143 , can we add/update a test here for this check

added tests

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
