### PR TITLE
limit port input value

### PR DESCRIPTION
**Pull request by christianvogt**
## Fixes 

https://issues.redhat.com/browse/STONEBUGS-92

## Description

use html input attributes `min` and `max` to limit the port number input values

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

no visual change

## How to test or reproduce?

edit the target port of a component using built in input arrows: 
image

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
What is the need of empty analytics file? Seems like it got into this commit by mistake.

**Comment by christianvogt** [comment]
@rohitkrai03 i suspended other changes i was working on to go rebase this one. I didn't realize that got into the mix. I'll fix that now

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
