### PR TITLE
feat(secrets): remove deployments from secrets

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-5711

## Description

- Refactor Add secret form to remove the Deployment option from it.
- Remove mention of deployments from the Secret list page

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2024-04-23 at 7 01 46 PM
Screenshot 2024-04-17 at 7 03 39 PM

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
- On the list page we do not need the secrets for column now.
- Also the status is related to remote secrets status so it better to remove that as well.
- We'll need to remove all the deployment secrets related components and utils as well.

**Comment by abhinandan13jan** [comment]
> * On the list page we do not need the secrets for column now.
> * Also the status is related to remote secrets status so it better to remove that as well.
> * We'll need to remove all the deployment secrets related components and utils as well.

Removed
Screenshot 2024-04-23 at 7 01 46 PM

**Review by sahil143 — APPROVED** [review]
/lgtm

**Comment by rohitkrai03** [comment]
@abhinandan13jan You'll need to rebase the PR.

**Review by sahil143 — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
