### PR TITLE
Enable caddy config file so we can have better metrics

### PR DESCRIPTION
**Pull request by karelhala**
## Fixes 
https://issues.redhat.com/browse/HAC-2147

## Description

Platform is slowly adopting caddy config file (we are supporting both nginx and Caddy at the moment) in order to have easier metrics reports. This PR migrates nginx config to Caddy one (I kept the `/apps/hac-dev` in place as well, for backwards compatibility)

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## How to test or reproduce?

You can try it with this Dockerfile
```
FROM quay.io/cloudservices/caddy-ubi:357c825
COPY ./Caddyfile /opt/app-root/src/Caddyfile
COPY ./dist /opt/app-root/src/dist
COPY ./package.json /opt/app-root/src
WORKDIR /opt/app-root/src
CMD ["caddy", "run", "--config", "/opt/app-root/src/Caddyfile"]
```

### CODE REVIEW

**Review by BlakeHolifield — APPROVED** [review]

**Comment by BlakeHolifield** [comment]
@karelhala It looks like all the hac-dev pr checks are failing smoke tests. Looks like Pete was working on it, but I don't think this change is the issue.

**Comment by karelhala** [comment]
Re run tests

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by rohitkrai03** [comment]
@karelhala Is this PR still relevant?

**Comment by karelhala** [comment]
Yup @BlakeHolifield did some Caddy metrics a while back so it would be nice to collect them (it's basically a mirror to nginx config). Not sure why devshift failed. I'll try to reopen the PR and see if there are any errors.

**Comment by karelhala** [comment]
@rohitkrai03 Not sure why the ci.int is failing though.

**Comment by karelhala** [comment]
I'll open a new PR, looks like the test ran a while back and is not accessible anymore.

**Comment by rohitkrai03** [comment]
@karelhala The CI has been broken for a few weeks for us. QE team is working on getting it up and running.

**Pull request closed without merging**
