### PR TITLE
feat(dependencies): update package dependencies

### PR DESCRIPTION
**Pull request by rohitkrai03**
## Fixes 

- https://issues.redhat.com/browse/HAC-4268

## Description

- Updated dependencies for hac-dev.
- Updated to react 18 and related fixes.

## Type of change

- [x] Build related changes

## How to test
- Pull in the hac-core PR - https://github.com/openshift/hac-core/pull/147.
- Run hac-core locally with `LOCAL_HAC_DEV=true ENVIRONMENT=prod yarn dev`.
- Pull in this PR locally.
- Update node to 18 LTS and npm to 9.x.
- Re-install the node packages.
- Run hac-dev with PR branch using `npm run start:federated`.

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
Getting errors when I try `npm install`:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @openshift/dynamic-plugin-sdk-extensions@1.3.0
npm ERR! Found: react-router@6.3.0
npm ERR! node_modules/react-router
npm ERR!   react-router@"6.3.0" from react-router-dom@6.3.0
npm ERR!   node_modules/react-router-dom
npm ERR!     react-router-dom@"6.3.0" from the root project
npm ERR!     peer react-router-dom@"^6.3.0" from @openshift/dynamic-plugin-sdk-utils@4.0.0
npm ERR!     node_modules/@openshift/dynamic-plugin-sdk-utils
npm ERR!       @openshift/dynamic-plugin-sdk-utils@"^4.0.0" from the root project
npm ERR!     2 more (@redhat-cloud-services/frontend-components, @redhat-cloud-services/frontend-components-utilities)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react-router@"^5.2.1" from @openshift/dynamic-plugin-sdk-extensions@1.3.0
npm ERR! node_modules/@openshift/dynamic-plugin-sdk-extensions
npm ERR!   @openshift/dynamic-plugin-sdk-extensions@"^1.3.0" from the root project
npm ERR!   peer @openshift/dynamic-plugin-sdk-extensions@"^1.3.0" from @openshift/dynamic-plugin-sdk-utils@4.0.0
npm ERR!   node_modules/@openshift/dynamic-plugin-sdk-utils
npm ERR!     @openshift/dynamic-plugin-sdk-utils@"^4.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-router@5.3.4
npm ERR! node_modules/react-router
npm ERR!   peerOptional react-router@"^5.2.1" from @openshift/dynamic-plugin-sdk-extensions@1.3.0
npm ERR!   node_modules/@openshift/dynamic-plugin-sdk-extensions
npm ERR!     @openshift/dynamic-plugin-sdk-extensions@"^1.3.0" from the root project
npm ERR!     peer @openshift/dynamic-plugin-sdk-extensions@"^1.3.0" from @openshift/dynamic-plugin-sdk-utils@4.0.0
npm ERR!     node_modules/@openshift/dynamic-plugin-sdk-utils
npm ERR!       @openshift/dynamic-plugin-sdk-utils@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/msaud/.npm/_logs/2023-10-20T14_47_55_963Z-eresolve-report.txt
```
With versions:
```
λ  node --version
v18.18.2
λ  npm --version
9.8.1
```

**Comment by rohitkrai03** [comment]
@rottencandy The e2e tests will fail until we merge https://github.com/openshift/hac-core/pull/147.

**Pull request merged**
