### PR TITLE
Set git branch & context fields if present in url

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-270

## Description
If the git url contains branch & context segments, use that to fill the reference & context directory fields.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://github.com/openshift/hac-dev/assets/20013884/260d0573-a858-451c-99dc-b258dbc8b9cd

## How to test or reproduce?
Use a git url with context/path segments.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
@rottencandy After adding full url with context & revision, then for some reason if the user decides to delete the revision and context part (`/tree/main/public`) from the url `https://github.com/karthikjeeyar/dc-metro-map/tree/main/public`, then I think we should reset the `revision` and `context` back to empty strings. Right now it is still showing the previous values in those fields.

**Comment by rottencandy** [comment]
Updated to reset the fields if URL doesn't contain revision or context.

**Pull request merged**
