### PR TITLE
remove selectable from component settings card

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-2998

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-02-17 at 7 09 35 PM

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
Looks like we don't get the blue highlight on the left with this

**Comment by christianvogt** [comment]
No blue line (at the top) is fine. This isn't a selectable card. It's just expandable. This aligns with the samples in patternfly.

before:
image

**Pull request merged**
