### PR TITLE
Add filter to pipelinerun link data

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-26

## Description
Add filter to link data for PIpelineRun node.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/20013884/235201161-8766e534-5273-48dd-9c8c-141c8fee4a5e.mp4

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]
/lgtm

**Comment by rottencandy** [comment]
Added tests to satisfy codecov

**Pull request merged**
