### PR TITLE
change browser tab title based on different views

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/HAC-2702

## Description

updates page title based on the view.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
Do we need one for component settings page?

Right now it says `My Application - Components | Stonesoup`

**Comment by sahil143** [comment]
@rottencandy I have fixed it.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Pull request merged**
