### PR TITLE
Remove environments page help topic link

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-218

## Description
Remove help topic link from environments page

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/cc @rohitkrai03

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

**Comment by rohitkrai03** [comment]
/hold

For ack from consoledot.

**Comment by rottencandy** [comment]
Got ack from consoledot

/hold cancel

**Comment by rottencandy** [comment]
Had to fix merge conflict

**Pull request merged**
