### PR TITLE
Added Option to run all e2e test suite on pr check

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Fixes 

https://issues.redhat.com/browse/HAC-3684

## Description

Added Option to run all e2e test suite on pr check

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Test

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by subhashkhileri** [comment]
/retest
alltest

**Comment by subhashkhileri** [comment]
retest

**Comment by subhashkhileri** [comment]
test

**Comment by jrichter1** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test] all

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
hold cancel

**Comment by subhashkhileri** [comment]
[test]

**Pull request merged**
