### PR TITLE
Add component details page

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-4534](https://issues.redhat.com/browse/HAC-4534)

## Description
Adds a component details page that includes details and activities for the component.

## Type of change
- [x] Feature

## Screen shots / Gifs for design review 

image

image

image

image

/cc @Ranelim @Misjohns

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
UI broke with the following error in console for a sample go component.
```
VM41380:1 Caught error in a child component: TypeError: Cannot read properties of undefined (reading 'application')
    at ComponentLatestBuild (ComponentLatestBuild.tsx:178:90)

**Comment by Misjohns** [comment]
@jeff-phillips-18 I've marked up a number of fit and finish items and reviewed with Ran. Please let me know if you have any questions.

image

**Comment by Misjohns** [comment]
@jeff-phillips-18 We may not need it now. In the future when users have more environments it could be useful.

**Comment by jeff-phillips-18** [comment]
@Misjohns The `Edit deployment settings` from this page will be a separate story (I tried to limit the size of this PR, but alas...). However, in the design it showed the edit as a secondary button below the settings. Which is correct?

**Comment by jeff-phillips-18** [comment]
Updated per UX comments. @Misjohns @Ranelim Please take a look at updated screen shots.

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar Rebased

**Pull request merged**
