### PR TITLE
fix(test): update pipeline labels

### PR DESCRIPTION
**Pull request by jrichter1**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-877

## Description
pipeline & build service got updated, some labels/names got changed, update the e2e tests

### CODE REVIEW

**Comment by jrichter1** [comment]
[test]

**Comment by jrichter1** [comment]
[test]

**Comment by jrichter1** [comment]
[test]

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
