### PR TITLE
Inform user when target port is not detected

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [RHTAPBUGS-140](https://issues.redhat.com/browse/RHTAPBUGS-140)

## Description
Adds message text when target port cannot be detected.

## Type of change
- [x] Bugfix

## Screen shots / Gifs for design review 
image

/cc @karthikjeeyar @rohitkrai03 @misjohns

### CODE REVIEW

**Comment by Misjohns** [comment]
@jeff-phillips-18 Consensus was to change the error to "We can't detect your target port. Check if it's correct."

**Review by rottencandy — APPROVED** [review]
/lgtm

**Pull request merged**
