### PR TITLE
Redesigned and refactored new import flow

### PR DESCRIPTION
**Pull request by rohitkrai03**
## Fixes 

- https://issues.redhat.com/browse/HAC-3660

## Description

- Updated the import flow to new design.
- Refactored the components based on new flow and removed FormikWizard.

## Type of change

- [x] Feature

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/6041994/235164417-ce0b37c9-9fc7-4eca-abc6-e7494807f767.mov

## TODO
- [ ] Fix e2e tests.

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
If I change app name, runtime detection gets triggered

https://user-images.githubusercontent.com/20013884/235178494-8940d0ce-9189-4eee-bfb8-af352e2b26eb.mp4

If I go back when runtime detection is in progress, the import button stays disabled

https://user-images.githubusercontent.com/20013884/235178671-aec49e89-e3a0-4237-bc60-0cadc54025fc.mp4

**Comment by jrichter1** [comment]
After I input a valid repo and make a change to the URL, it lets me proceed even if the repo is no longer valid
[Screencast from 05-02-2023 09:28:09 AM.webm](https://user-images.githubusercontent.com/4181232/235606360-edd044e1-d516-4fc8-838d-97874544f3fb.webm)

**Comment by jrichter1** [comment]
also the help/docs in the `Learn more` section will need updates

**Comment by jrichter1** [comment]
There is also no way to name a new application when creating it with a sample component.

**Comment by jrichter1** [comment]
Some shenanigans with runtime selection:
 - manually selecting dockerfile prevents from going back to the recommended runtime
 - selecting something else and going back to the recommended runtime just hangs the runtime detection

[Screencast from 05-02-2023 11:43:06 AM.webm](https://user-images.githubusercontent.com/4181232/235634268-7bcbdb09-40b0-4ad4-8f45-512b3cefd8a4.webm)
(I've cut it short, but it's been going for 10 minutes at least)

**Comment by rohitkrai03** [comment]
> If I change app name, runtime detection gets triggered
> 
>  recording-1682692369.mp4 
> If I go back when runtime detection is in progress, the import button stays disabled
> 
>  recording-1682692800.mp4

@rottencandy Fixed the issues.

**Comment by rohitkrai03** [comment]
> After I input a valid repo and make a change to the URL, it lets me proceed even if the repo is no longer valid
> 
>  Screencast.from.05-02-2023.09.28.09.AM.webm

@jrichter1 Fixed it.

**Comment by rohitkrai03** [comment]
> also the help/docs in the `Learn more` section will need updates

Yeah, docs team is working on updating the learn more topics.

**Comment by rohitkrai03** [comment]
> Some shenanigans with runtime selection:
> 
> * manually selecting dockerfile prevents from going back to the recommended runtime
> * selecting something else and going back to the recommended runtime just hangs the runtime detection
> 
>  Screencast.from.05-02-2023.11.43.06.AM.webm

Fixed it.

**Comment by Misjohns** [comment]
Spacing should be consistent within the containers. I'm using 64px spacing so it's not so tight.

Screen Shot 2023-05-02 at 1 01 29 PM

Screen Shot 2023-05-02 at 1 01 20 PM

**Comment by Misjohns** [comment]
For the secret section:

- Secret remove is too far away from the field; use same placement as the environment variable field placement.
- Secret fields are very long. Let's align those with the variable name field.

Secret bug

**Comment by Misjohns** [comment]
Import screen:
-  Git repository URL* and Context directory should both have a question mark icon that accesses a pop-over
- "Context dir" should be spelled out "Context directory"

Unable to access repo screen:
- We should not show the Git reference, Context directory or Import code button if the repo can't be accessed.

Screen Shot 2023-05-02 at 11 18 54 AM

Summit Access to repository fails

**Comment by Misjohns** [comment]
Samples:
Need to align the link buttons so cards are easier to scan
sample bug

**Comment by rohitkrai03** [comment]
> For the secret section:
> 
> * Secret remove is too far away from the field; use same placement as the environment variable field placement.
> * Secret fields are very long. Let's align those with the variable name field.
> 
> Secret bug

This PR doesn't have ability to add secrets. https://github.com/openshift/hac-dev/pull/595 adds that.

**Comment by Misjohns** [comment]
Component card:
- Runtime value does not need to be bold
- GH link does not need to be bold

Screen Shot 2023-05-02 at 1 41 52 PM

**Comment by rohitkrai03** [comment]
> Detecting values: We don't need 2 "detecting…" screens. Let's keep the background overlay with "Detecting values…" message on card until we can load the components.
> 
> Screen Shot 2023-05-02 at 1 22 30 PM
> 
> image

We cannot do this. Importing sample and importing git repos is two different forms put together now. We need to detect values for git repo on the review page because we have a runtime selector that can be used to change the detected values. Changing the runtime from selector triggers the same CDQ detection. That's why we cannot detect the values on the source step and move to review only after detection completes. We would need a consistent progress mechanism for when user first land and CDQ happens and also when user changes the runtime and CDQ happens. 
We could add the backdrop version on review page though but I feel that could be too in your face to disable everything and show spinner when user just changed the runtime.

Also, the spinner on samples flow says `Importing sample...` and not `Detecting value...` because user doesn't need to know what we're doing under the hood (running detection and importing sample). He just knows that he clicked on `Import sample` so the progress bar should convey that his action is in progress.

**Comment by rohitkrai03** [comment]
> @rohitkrai03 Based on your comment "We would need a consistent progress mechanism for when user first land and CDQ happens and also when user changes the runtime and CDQ happens." Can you please share video of changing the runtime and CDQ happens, so I can see the progress message?

@Misjohns This is how it looks if we use the backdrop version on the review page as well.

https://user-images.githubusercontent.com/6041994/235758600-79ec769b-ce49-40c6-9db9-58b2521bbdac.mov

**Comment by Misjohns** [comment]
@rohitkrai03 The new card version is much better. The initial version looked like an empty state with that extra copy which doesn't add much value if the user doesn't have time to read it.

**Comment by rohitkrai03** [comment]
> Spacing should be consistent within the containers. I'm using 64px spacing so it's not so tight.
> 
> Screen Shot 2023-05-02 at 1 01 29 PM
> 
> Screen Shot 2023-05-02 at 1 01 20 PM

@Misjohns Added consistent spacing within the container. Based on internal padding and margin standards, I've set the padding top for the icon and padding bottom for the CTA buttons within the container to `pf-u-pt-lg` and `pf-u-pb-lg`.

Screenshot 2023-05-03 at 1 03 48 AM

Screenshot 2023-05-03 at 1 03 28 AM

**Comment by rohitkrai03** [comment]
> Import screen:
> 
> * Git repository URL* and Context directory should both have a question mark icon that accesses a pop-over
> * "Context dir" should be spelled out "Context directory"
> 
> Unable to access repo screen:
> 
> * We should not show the Git reference, Context directory or Import code button if the repo can't be accessed.
> 
> Screen Shot 2023-05-02 at 11 18 54 AM
> 
> Summit Access to repository fails

@Misjohns Done.

https://user-images.githubusercontent.com/6041994/235768285-34552175-b7a2-4216-963d-283c01f8e12d.mov

**Comment by rohitkrai03** [comment]
> Samples: Need to align the link buttons so cards are easier to scan sample bug

@Misjohns Done.

Screenshot 2023-05-03 at 1 04 12 AM

**Comment by rohitkrai03** [comment]
> Component card:
> 
> * Runtime value does not need to be bold
> * GH link does not need to be bold
> 
> Screen Shot 2023-05-02 at 1 41 52 PM

@Misjohns Done.
Screenshot 2023-05-03 at 1 04 43 AM

**Review by karthikjeeyar — APPROVED** [review]
/lgtm

**Pull request merged**
