### PR TITLE
Integration test git resolver support

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-3243
https://issues.redhat.com/browse/HAC-3240
https://issues.redhat.com/browse/HAC-3241

## Description

- Updates type of IntegrationTestScenario Kind to ResolveRef
- Adds util functions for parameter and Resolver support
- Updates DetailsPage for ITS
- Updates Create/Edit form of IntegrationTestDetails Page to support git resolver
- Updates List View for Integration Test
- Updates and adds unit test suites

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### create/edit form
------------------------
Screenshot 2023-04-27 at 5 25 03 PM
Screenshot 2023-04-27 at 5 24 34 PM

---------------------------------
### List view using mock data
------------------------------
Screenshot 2023-04-27 at 6 36 11 PM

-----------------------------------
### Details view and linked page using mock data
------------------------------------
Screenshot 2023-04-27 at 6 14 44 PM
Screenshot 2023-04-27 at 6 15 04 PM

-----------------------
### API response and k8sResource creation(currently failing)

Screenshot 2023-04-27 at 5 25 41 PM
Screenshot 2023-04-27 at 5 27 06 PM
----------------------------

## How to test or reproduce?

Updated unit tests

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
@abhinandan13jan You need to change the apiVersion from `v1` to `v1beta1`, which contains the git resolver change. 
cc: @jsztuka

**Comment by karthikjeeyar** [comment]
UI should not break If I add bundle resolver via cli,

Screenshot 2023-05-30 at 7 35 52 PM

**Comment by karthikjeeyar** [comment]
@abhinandan13jan https://github.com/openshift/hac-dev/pull/685 is merged now and it contains above commits. you can close this PR now.

**Comment by abhinandan13jan** [comment]
Closing as it is merged via https://github.com/openshift/hac-dev/pull/685

**Pull request closed without merging**
