### PR TITLE
Use new git location for ec pipeline definition

### PR DESCRIPTION
**Pull request by simonbaird**
## Fixes 

* https://issues.redhat.com/browse/EC-668

## Description

The build-definitions repo moved over to the new konflux-ci org in GitHub. Update the pipeline definition git resolver url accordingly.

## Type of change

One-liner to update a git url.

## Screen shots / Gifs for design review 

Should be zero visible change.

## How to test or reproduce?

I expect the risk is almost zero here. CI might be enough, but to test it, create a component and make sure the automatically created Enterprise Contract Integration Test Scenario is create and runs as expected.

### CODE REVIEW

**Review by sahil143 — APPROVED** [review]

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Comment by simonbaird** [comment]
This should be an easy-merge I think. Does it really need two more reviews? Anyone want to hit the merge button?

**Comment by simonbaird** [comment]
To confirming the url change, try clicking https://github.com/redhat-appstudio/build-definitions and notice where you end up.

**Comment by simonbaird** [comment]
https://github.com/konflux-ci/build-definitions/blob/main/pipelines/enterprise-contract.yaml is the pipeline being referenced in that repo for the integration test.

**Comment by zregvart** [comment]
The problem here is that the "Red Hat Konflux" check suite is [demanding](https://github.com/openshift/hac-dev/pull/957/checks?check_run_id=26781806178) something from someone, and apparently no one knows what that is:

```
User simonbaird is not allowed to trigger CI via pull_request on this repo.
```

**And** tide is (mis)configured to merge only if "Red Hat Konflux" check suite is marked as successful.

**Comment by simonbaird** [comment]
Thanks @rohitkrai03 .

**Pull request merged**
