### PR TITLE
Change test output failures to convey warning

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-3509](https://issues.redhat.com/browse/HAC-3509)

## Description
Change conveyed status for test failures on task runs to warning.
Set the warning badge to the sum of both failures and warnings.
Update text for test failures to show as `Test failures` or `Test warnings` in task run list.

## Type of change
- [x ] Bugfix

## Screen shots / Gifs for design review 

image

image

/cc @karthikjeeyar @christianvogt @andrew-ronaldson

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
> just saw that the label in the sidepanel is grey when in warning state:

We can take another look at the `<StatusIconWithTextLabel>` component. But this was not changed by this PR.

**Comment by christianvogt** [comment]
/lgtm

We can followup with UX later on this. Perhaps just log a bug about it and tag UX to see if a change is or isn't requested.

**Review by andrew-ronaldson — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
