### PR TITLE
Always allow component creation if dockerfile runtime is selected

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-469

## Description
Always allow component creation if dockerfile runtime is selected.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://github.com/openshift/hac-dev/assets/20013884/eb951d2f-5c75-4501-93dd-e63e2ce1a7b8

## How to test or reproduce?
Use a repo that returns error when detection, and select dockerfile runtime.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rohitkrai03** [comment]
Even after selecting Dockerfile runtime the create button doesn't get enabled. I have to touch the dockerfile and port fields to enable it.

https://github.com/openshift/hac-dev/assets/6041994/017f92fa-fa57-4b31-9a6a-35c9af24586c

**Comment by rottencandy** [comment]
Looks like that  was the bug which was fixed in https://github.com/openshift/hac-dev/pull/739, I rebased and it's working fine now.

**Review by rohitkrai03 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
