### PR TITLE
Add release object list & details pages

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-4086
https://issues.redhat.com/browse/HAC-4087

## Description
Add release objects pages.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## How to test or reproduce?
Set up releases: https://gist.github.com/rottencandy/372135fbef5f8530f748eb3abedf8fe2

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
Forgot about empty state :p

Added a generic message:


cc @beaumorley @misjohns

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by wolfeallison** [comment]
@rottencandy - for the release empty state, how does the user set up a release plan for their applications? Could we add a button that directs them to set up a release plan? I believe the empty states on the other tabs have buttons, so I think it could be good to add one to match. 

Also, maybe a definition of "release" could be good. How would you define "release" here? 

Copy for release empty state: 
**Check out all of your releases**
A release is a -----------. To view your releases, set up a release plan for your application.
[Set up release plan]

**Comment by rottencandy** [comment]
@wolfeallison we don't yet have any method of creating releases/release plans through the UI, not sure if it would be possible to have a button here.

But we can update the copy for empty state regardless, created a ticket:

**Pull request merged**
