### PR TITLE
Refactor pipeline run visualization

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Description
Refactor the pipeline run visualization and remove extraneous code. 
The hook for useCommitWorkflowData in application details is no longer used.
The method for determining the last environment was building a full topological view just to determine the last env.
Removing DAG in lieu of just creating the node models and using the PF topology methods for creating edges and spacers.

## Type of change
- [x] Refactoring (no functional changes, no api changes)

/cc @karthikjeeyar @christianvogt

### CODE REVIEW

**Review by karthikjeeyar — APPROVED** [review]
/approve
/lgtm

**Comment by jeff-phillips-18** [comment]
Added more tests to get project coverage to pass

**Pull request merged**
