### PR TITLE
e2e: PF5 upgrade fix

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Fixes 

https://issues.redhat.com/browse/HAC-4843

## Description

Update the locators in tests to PF5.

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Test

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by jrichter1** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Comment by subhashkhileri** [comment]
[test]

**Pull request merged**
