### PR TITLE
Add PR check and build deploy scripts

### PR DESCRIPTION
**Pull request by karelhala**
## Description
Add pr_check and build deploy scripts. Once this repository is onboarded to app-sre we will have automatic image releases enabled.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by karelhala** [comment]
ping @psav

**Review by BlakeHolifield — APPROVED** [review]

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
