### PR TITLE
fix(import): Avoid resetting name input fields if modified

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-757
https://issues.redhat.com/browse/RHTAPBUGS-997

## Description
Avoid resetting the application name and component name fields if they'be been modified.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
No design changes

https://github.com/openshift/hac-dev/assets/20013884/a1dbcea0-cfad-4fd6-97d1-06e62d57b1d7

## How to test or reproduce?
Try to create an app that already exists, or change runtime after changing component name.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Comment by rottencandy** [comment]
/hold cancel

Had to fix application field from not getting cleared.

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
