### PR TITLE
update screen copies

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-2838

## Description

1. Updates "Name your application"
2. Remove "?"
3. Updates "Read more" -> "show more" -- portion is removed
4. Delete Application Modal: Change the label to "Type [application name] to confirm deletion:" 
5. App Overview tab > Lifecycle visualization: The "View in tab" links on Components and Static environments popovers should be more descriptive. ex. "View Components" "View Environments"
6. Components tab: Change "Component settings" in action menu to "Edit component settings"

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-02-01 at 8 56 42 PM
Screenshot 2023-02-01 at 8 58 59 PM
Screenshot 2023-02-02 at 8 34 48 PM
Screenshot 2023-02-02 at 8 34 54 PM
Screenshot 2023-02-02 at 8 35 13 PM
Screenshot 2023-02-02 at 8 35 31 PM

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by beaumorley** [comment]
This looks good. I do not see an example of the 'Updates "Read more" -> "show more" -- portion is removed'. Can you add a screen cap for that? Thank you!

**Comment by christianvogt** [comment]
@beaumorley it seems like that is no longer relevant as the original code was removed. Neither show more or read more is present.

**Comment by christianvogt** [comment]
It's not clear in the deletion label what the user has to type:

image

The name should be quoted. At least in the description there is a different in bold letters.
cc @beaumorley

**Comment by abhinandan13jan** [comment]
Added quotation in another commit. Do confirm.. @beaumorley 

Screenshot 2023-02-06 at 7 31 12 PM

**Comment by rohitkrai03** [comment]
@abhinandan13jan You have e2e test failures caused by the changes in this PR.

**Pull request merged**
