### PR TITLE
Replace component detection mock data with calls to ComponentDetectionQuery

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-438

## Description

Remove git source detection mock data and use ComponentDetectionQuery creation to detect components in git import flow.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
(No UI changes)

## How to test or reproduce?
Example repo with single comopnent: https://github.com/devfile-samples/devfile-sample-python-basic
Example repo with multiple components: https://github.com/maysunfaisal/multi-components

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
@rottencandy for my user am getting 403 for  `componentdetectionqueries`

is there some prereq I need to do?

image

**Comment by karthikjeeyar** [comment]
While the component detection is happening, the `validating...` help text beneath the input field has red color text (could be misinterpreted as error). Shouldn't it be a default text color until it detects the component?

https://user-images.githubusercontent.com/9964343/151492304-b919abc0-98d1-4cb6-a2e8-6dc72b92f422.mov

**Pull request merged**
