### PR TITLE
use latest test pipelinerun status in lifecycle visualization

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/HAC-3484

## Description

Integration test nodes should use the latest test pipeline run status in the lifecycle visualization.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

Screenshot 2023-03-13 at 11 35 41 PM

## How to test or reproduce?

1. Add a failing integration test - https://quay.io/repository/redhat-appstudio/example-tekton-bundle?tab=tags&tag=integration-pipeline-fail.
2.  start a new build and wait for the build and test pipeline to complete
3. Then edit the integration pipeline to `integration-pipeline-pass`
4. start a new build again and wait for the build and test pipeline to complete
5. lifecycle visualization should show the latest succeeded pipeline status.

## Unit tests

```
  useAppApplicationTestNodes
    ✓ should return integration test nodes (35 ms)
    ✓ should return failed status (9 ms)
    ✓ should return status from latest pipelinerun (10 ms)

```

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by karthikjeeyar** [comment]
Rebased the PR.

**Pull request merged**
