### PR TITLE
Rename environments tab to deployments

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-188

## Description
Rename application environments tab to deployments, update microcopy, add route link to cards, fix urls

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by pankajshivpuje** [comment]
Looks good to me. @Ranelim @beaumorley  Can you take a look at the screenshot for implemented deployment tab?

**Comment by rottencandy** [comment]
- Removed first sentence under title
- Removed apps deployed from cards in deployments tab

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
- We've renamed the tab to `Deployments` but the actual information that is being shown is still about environments.
- We are showing a page title `Deployments` and then adding a description below that explain what is an environment. Shouldn't we explain what deployments are and how we are showing deployments in this page?
- The view URL CTA is the same route that is being shown in the header of the application details page. How does it add value here?

cc: @Ranelim @beaumorley

**Comment by beaumorley** [comment]
If you look at the design doc, there is updated copy that explains deployment. I would recommend putting in the updated copy. This is definitely a crawl. We will evolve this tab to add more value.

**Comment by rottencandy** [comment]
Moved [RHTAPBUGS-218](https://issues.redhat.com/browse/RHTAPBUGS-218) related changes to https://github.com/openshift/hac-dev/pull/625 since that doesn't need design changes.

**Comment by rottencandy** [comment]
Updated deployments tab text to `Manage snapshots and their deployment to environments. An environment is a set of compute resources that you can use to develop, test and stage your application. A snapshot is a set of all recent builds, automatically created on every new build.`

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

**Comment by rottencandy** [comment]
Got ack from consoledot

/hold cancel

**Comment by Ranelim** [comment]
@rottencandy @rohitkrai03 
Microcopy update:
"Manage your snapshots and their deployment to environments. An environment is a set of compute resources that you can use to develop, test, and stage your application. A snapshot is a set of component and container images that specifies which components the system should deploy with which container images. The system creates a snapshot when it finishes running a component’s build pipeline."

**Pull request merged**
