### PR TITLE
feat(snapshot): add environment provision error

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-4941

## Description

Reads Environment provision error from snapshot annotation and displays if error exists.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
Screenshot 2023-10-30 at 8 48 55 PM
Screenshot 2023-10-30 at 8 48 59 PM
Screenshot 2023-10-30 at 8 49 08 PM

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by Misjohns** [comment]
Here are some UX recommendations. I also would like Allison to take a look at updating the microcopy of the error.
image

**Comment by abhinandan13jan** [comment]
@Misjohns updated
Screenshot 2023-10-30 at 6 01 54 PM
Screenshot 2023-10-30 at 6 01 58 PM
Screenshot 2023-10-30 at 6 35 32 PM

**Comment by Misjohns** [comment]
@abhinandan13jan We can remove the error from the box. Just need the error icon and the content.

**Comment by abhinandan13jan** [comment]
> @abhinandan13jan We can remove the error from the box. Just need the error icon and the content.

Can you please point me to the Patternfly component we are referring to? I am not able to find any such alerts

**Comment by abhinandan13jan** [comment]
@Misjohns updated
Screenshot 2023-10-30 at 8 48 55 PM
Screenshot 2023-10-30 at 8 48 59 PM
Screenshot 2023-10-30 at 8 49 08 PM

**Review by jeff-phillips-18 — APPROVED** [review]

**Pull request merged**
