### PR TITLE
return users to last used sub tab on activity tab selection

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-161

## Description

I often want to visit the pipeline runs within the activity tab. However every time I visit the activity tab, it displays the commits sub tab by default. It would be useful if clicking the activity tab brought the user back to the previously viewed sub tab.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/9964343/233547956-9f0d7509-54be-4027-8ccf-638628ea443b.mov

## How to test or reproduce?

1. Select Activity tab, and select pipelineruns tab 
2. Go to any other tab and return back to activity tab, the pipelineruns tab should be pre selected

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

cc: @christianvogt

### CODE REVIEW

**Comment by christianvogt** [comment]
@karthikjeeyar you need to push the subtab into the url upon first navigation because right now the back button navigation does not go back to the previous tab.

**Comment by karthikjeeyar** [comment]
Fixed it. Pushing the subtab in the url to support back button navigation.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Comment by karthikjeeyar** [comment]
@rottencandy I have made changes to tab data-test id logic that caused e2e failure.

**Review by rottencandy — APPROVED** [review]
/lgm

**Pull request merged**
