### PR TITLE
fix(PrivateAuth): remove feature flag from auth flow

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/KFLUXBUGS-1260
https://issues.redhat.com/browse/KFLUXBUGS-1259

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
need tests for codecov

**Comment by abhinandan13jan** [comment]
code looks good, kindly fix the codecov requirement

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
