### PR TITLE
update validation text

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-2784

## Description

Updates text for SourceSection validation

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-01-12 at 7 06 50 PM
Screenshot 2023-01-12 at 7 07 06 PM

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
@abhinandan13jan Unit tests are failing, I think you missed one more occurrence in the spec file.

**Comment by rohitkrai03** [comment]
Hey, I've merged the PR that fixed the e2e tests - #305. So going forward it would be good to run the e2e tests locally and paste the screenshot here on the PR before merging. Can you do that?

**Comment by abhinandan13jan** [comment]
@karthikjeeyar updated

**Comment by rohitkrai03** [comment]
@abhinandan13jan Can you add e2e test run screenshots?

**Comment by rohitkrai03** [comment]
Can you investigate why it is timing out? Maybe run on main branch to see if its an issue with your PR?

**Comment by abhinandan13jan** [comment]
I am able to run them individually and the 3 passes. . Should that be good for the PR? will check why the timeout happens
Screenshot 2023-01-18 at 10 03 14 PM
Screenshot 2023-01-18 at 10 09 49 PM
Screenshot 2023-01-18 at 10 01 30 PM

**Pull request merged**
