### PR TITLE
Switch to new build request system annotations

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-4229

## Description
Switch to using new build request system annotations and update utils to use new build status format.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
(No UI changes)

## How to test or reproduce?
Use all methods of configuring PaC.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
Waiting for configure-time build status field to be available [STONEBLD-1522](https://issues.redhat.com/browse/STONEBLD-1522)

/hold

**Comment by rottencandy** [comment]
Configure-time build status is now available.

/hold cancel

**Review by rohitkrai03 — COMMENTED** [review]
/approve

**Pull request merged**
