### PR TITLE
Run docker as host user.

### PR DESCRIPTION
**Pull request by Katka92**
## Description
Run tests in a docker as a host user. Currently, if a job is interrupted during running tests, Jenkins fails to remove files generated by this test. Running as a host user should help to solve that.

### CODE REVIEW

**Comment by dheerajodha** [comment]
@Katka92 I looked at the PR build failures and noticed that the hacbs test is failing in all of them.
The test is not able to locate the "Add Component" button in both the ["Overview" tab](https://ci.int.devshift.net/job/openshift-hac-dev-pr-check/1291/artifact/artifacts/screenshots/hacbs/add-component-to-application-via-hacbs-tab.spec.ts/Create%20Components%20using%20the%20HACBS%20UI%20--%20Add%20a%20new%20component%20using%20the%20Overview%20tab%20--%20Add%20a%20component%20to%20Application%20(failed).png) and ["Component" tab](https://ci.int.devshift.net/job/openshift-hac-dev-pr-check/1291/artifact/artifacts/screenshots/hacbs/add-component-to-application-via-hacbs-tab.spec.ts/Create%20Components%20using%20the%20HACBS%20UI%20--%20Add%20a%20new%20component%20using%20the%20Components%20tab%20--%20Add%20a%20component%20to%20Application%20(failed).png).
Maybe because there are already a few things loading on the page, so it needs to ideally wait for the entire page to get loaded properly. Wdyt?

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
