### PR TITLE
fix(test): stabilise vulnerabilities 

### PR DESCRIPTION
**Pull request by Katka92**
## Description
Advanced Happy Path test suite is constantly failing during the nightly job to load the Vulnerabilities. Stabilize the loading of Vulnerabilities by refreshing the page during the Advanced Happy Path test suite.

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by Katka92** [comment]
[test]

**Comment by karthikjeeyar** [comment]
[test]

**Pull request merged**
