### PR TITLE
feat(STONEINTG-837): update url of redhat-appstudio/integration-examples

### PR DESCRIPTION
**Pull request by hongweiliu17**
* update url of redhat-appstudio/integration-examples since it is migrated to konflux-ci

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

## Fixes 
[STONEINTG-837](https://issues.redhat.com/browse/STONEINTG-837)

## Description
update url of redhat-appstudio/integration-examples since it is migrated to konflux-ci

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by hongweiliu17** [comment]
[integration-examples](https://github.com/konflux-ci/integration-examples) has been migrated to `konflux-ci`, can anyone help to review this PR? Thanks!

**Comment by rohitkrai03** [comment]
@Katka92 @jrichter1 Can one you guys verify and add your approval to the PR?

**Pull request merged**
