### PR TITLE
Add ContextSwitcher component

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-2309

## Description
- Create a generic ContextSwitcher component for workspaces and applications
- Use ContextSwitcher to implement application switcher in applications list page

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/20013884/199749526-151cfcc8-2550-48c5-bc39-e8a4cc02256f.mp4

## How to test or reproduce?
Click on context switcher next to application name breadcrumb.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
cc @openshift/team-hacdev-ux

**Comment by itsptk** [comment]
@rottencandy Could we keep the icon button, even in a loading state? The spinner that momentairly replaces it is sort of distracting. 

image

**Comment by rottencandy** [comment]
Removed the spinner. Now the switcher momentarily shows an empty list while the resources are fetched.

https://user-images.githubusercontent.com/20013884/201172440-6a41e0a2-ad79-4862-a2a3-f2d975a496ca.mp4

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
