### PR TITLE
Use pipelinerun with scan status for commits & integration tests tabs

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/RHTAPBUGS-255

## Description
The pipelinerun scan status row was recently updated to use pipelinerun object with augmented scan status, but the commits & integration tests tabs were not updated along with it.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/cc @jeff-phillips-18 @rohitkrai03

### CODE REVIEW

**Comment by rottencandy** [comment]
Can we do conditional label filtering using the API? I wasn't able to find a way for this
```ts
      pipelineRunsWithStatus?.filter(
        (plr) =>
          plr?.metadata?.labels[PipelineRunLabel.COMMIT_LABEL] === commitName ||
          plr?.metadata?.labels[PipelineRunLabel.TEST_SERVICE_COMMIT] === commitName,
      ) || [],
```

**Comment by christianvogt** [comment]
@rottencandy yes you can use `matchExpressions` with operators in selectors.
I'm going to log a separate bug to capture improvements in our queries

**Pull request merged**
