### PR TITLE
Update the help toppic ids for whats next section

### PR DESCRIPTION
**Pull request by rohitkrai03**
## Fixes 

- https://issues.redhat.com/browse/HAC-3124

## Description

- Update the help topic ids in whats next section based on changes in https://github.com/RedHatInsights/quickstarts/pull/58.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

No UI change.

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rohitkrai03** [comment]
/hold

Waiting on the help topic content to get reflected in the UI.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Pull request merged**
