### PR TITLE
added codecov configuration

### PR DESCRIPTION
**Pull request by sawood14012**
## Description
added some configuration that might be required to fix the codecov uploading

## Type of change

- [X] Bugfix

### CODE REVIEW

**Comment by jrichter1** [comment]
nice :)

/lgtm

**Review by rhopp — APPROVED** [review]

**Review by rhopp — APPROVED** [review]

**Comment by sawood14012** [comment]
closing this PR as all my squashing attempts failed please look at the fresh PR https://github.com/openshift/hac-dev/pull/20

**Pull request closed without merging**
