### PR TITLE
add solution field to EC results expanded section

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-445

## Description

add solutions to EC results

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image
-------------------------------
image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by sahil143** [comment]
retest

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
