### PR TITLE
Change stonesoup url to application-pipeline

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-3584](https://issues.redhat.com/browse/HAC-3584)

## Description
Changes the `stonesoup` segment of the URL to `application-pipeline`. Redirects any URLs with stonesoup to the new URL.

## Type of change
- [x] Refactoring (no functional changes, no api changes)

/cc @rohitkrai03 @karthikjeeyar

### CODE REVIEW

**Comment by florkbr** [comment]
@jeff-phillips-18 looks like the latest run failed in E2E:
```bash
11:55:30   1) Create Component from Private Git Using Login Form
11:55:30        Creating Component From Private Github Repo
11:55:30          Works After Signing in to Github:
11:55:30      AssertionError: Timed out retrying after 40000ms: Expected to find element: `[data-test="details__tabItem components"]`, but never found it.
11:55:30       at ./utils/Applications.ts.Applications.goToComponentsTab (webpack:///./utils/Applications.ts:113:7)
11:55:30       at Context.eval (webpack:///./tests/create-application-from-private-git-form.spec.ts:89:21)
11:55:30 
11:55:30   2) Create Component from Private Git Using Login Form
11:55:30        Creating Component From Private Github Repo
11:55:30          "after all" hook for "Works After Signing in to Github":
11:55:30      TypeError: $el.css is not a function
11:55:30 
11:55:30 Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Create Component from Priva...`
11:55:30       at elHasDisplayNone (https://env-ephemeral-dovjpb-6mlz646c.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/__cypress/runner/cypress_runner.js:163133:14)
11:55:30       at Object.getReasonIsHidden (https://env-ephemeral-dovjpb-6mlz646c.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/__cypress/runner/cypress_runner.js:163380:7)
11:55:30       at Object.onError (https://env-ephemeral-dovjpb-6mlz646c.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com/__cypress/runner/cypress_runner.js:131258:81)
```

**Comment by christianvogt** [comment]
@jeff-phillips-18 no redirect from `stonesoup` is happening.

**Comment by jeff-phillips-18** [comment]
@christianvogt Fixed, change got lost in the rebase.

**Pull request merged**
