### PR TITLE
Upgrade formik-pf to bring fix for submit issue

### PR DESCRIPTION
**Pull request by rohitkrai03**

### CODE REVIEW

**Review by rottencandy — APPROVED** [review]
/lgtm

**Comment by rottencandy** [comment]
@rohitkrai03 looks like e2e tests are failing because triggering next button click doesn't work anymore, I replaced all `.trigger('click')` calls with `.click({ force: true })` and it seems to work:
```diff
diff --git a/integration-tests/support/pages/AddComponentPage.ts b/integration-tests/support/pages/AddComponentPage.ts
@@ -34,7 +34,7 @@ export class AddComponentPage extends AbstractWizardPage {
   }
 
   clickNext() {
-    cy.get(addComponentPagePO.next).trigger('click');
+    cy.get(addComponentPagePO.next).click({ force: true });
   }
 
   loginByToken(username: string, token: string){
diff --git a/integration-tests/support/pages/ComponentsPage.ts b/integration-tests/support/pages/ComponentsPage.ts
@@ -76,7 +76,7 @@ export class ComponentPage extends AbstractWizardPage {
   }
 
   createApplication() {
-    cy.get(ComponentsPagePO.create).trigger('click');
+    cy.get(ComponentsPagePO.create).click({ force: true });
     cy.get(ComponentsPagePO.create).should('be.disabled');
     Common.waitForLoad();
   }
diff --git a/integration-tests/support/pages/CreateApplicationPage.ts b/integration-tests/support/pages/CreateApplicationPage.ts
@@ -31,6 +31,6 @@ export class CreateApplicationPage extends AbstractWizardPage {
   }
 
   clickNext() {
-    cy.get(createApplicationPagePO.next).trigger('click');
+    cy.get(createApplicationPagePO.next).click({ force: true });
   }
 }
diff --git a/integration-tests/support/pages/hacbs/AddIntegrationTestPage.ts b/integration-tests/support/pages/hacbs/AddIntegrationTestPage.ts
@@ -14,7 +14,7 @@ export class AddIntegrationTestPage {
         cy.get(addIntegrationTestStepPO.optionalreleaseCheckbox).click();
     }
     clickNext() {
-        cy.get(addIntegrationTestStepPO.next).trigger('click');
+        cy.get(addIntegrationTestStepPO.next).click({ force: true });
     }
     clickAdd() {
         cy.get(addIntegrationTestStepPO.add).click();
diff --git a/integration-tests/support/pages/hacbs/CreateBuildPage.ts b/integration-tests/support/pages/hacbs/CreateBuildPage.ts
@@ -2,6 +2,6 @@ import { createBuildStepPO } from '../../pageObjects/hacbs-po';
 
 export class CreateBuildPage {
     clickNext() {
-        cy.get(createBuildStepPO.next).trigger('click');
+        cy.get(createBuildStepPO.next).click({ force: true });
     }
 }
diff --git a/integration-tests/utils/Applications.ts b/integration-tests/utils/Applications.ts
@@ -23,6 +23,7 @@ export class Applications {
     cy.testA11y(`${pageTitles.createApp} page`);
     createApplicationPage.setApplicationName(name);
     createApplicationPage.clickNext();
+    createApplicationPage.clickNext();
     cy.testA11y(`Select source form`);
   }
 }
```

**Comment by rottencandy** [comment]
@rohitkrai03 sorry I missed the hacbs pages, can you try these changes too
```diff
diff --git a/integration-tests/support/pages/ComponentsPage.ts b/integration-tests/support/pages/ComponentsPage.ts
index 1768341..1eb3416 100644
@@ -76,6 +76,7 @@ export class ComponentPage extends AbstractWizardPage {
   }
 
   createApplication() {
+    cy.get(ComponentsPagePO.create).click({ force: true });
     cy.get(ComponentsPagePO.create).click({ force: true });
     cy.get(ComponentsPagePO.create).should('be.disabled');
     Common.waitForLoad();
diff --git a/integration-tests/utils/HACBSApplications.ts b/integration-tests/utils/HACBSApplications.ts
index d0ce90a..41523ff 100644
@@ -106,6 +106,11 @@ export function addIntegrationTestStep(displayName: string, optionalForRelease:
     }
 
     cy.get('body').then(body => {
-        (body.find('button[type="submit"]').length > 0)? addIntegrationTestPage.clickNext() : addIntegrationTestPage.clickAdd();
+        if (body.find('button[type="submit"]').length > 0) {
+          addIntegrationTestPage.clickNext();
+          addIntegrationTestPage.clickNext();
+        } else {
+          addIntegrationTestPage.clickAdd()
+        };
     });
 }
```

**Comment by rohitkrai03** [comment]
Closing this PR for now. Will raise another one once we have the e2e tests fixed. This PR require updates to e2e tests and since they are already broken due to different reasons its hard to debug the issue.

**Pull request closed without merging**
