### PR TITLE
fix(add-snpshot-link): add snapshot link in pipelinerun details page

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-858

## Description

Build and test Pipelinerun details page should contain the snapshot section (if snapshot is available) and it should link us to the snapshot details page.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

https://github.com/openshift/hac-dev/assets/9964343/cb8e85c6-f2a9-4652-a9b5-cee0f1f60dfe

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Comment by mattreid** [comment]
@karthikjeeyar Thanks for picking this up! What happens when there's no snapshot information available?

**Comment by karthikjeeyar** [comment]
@mattreid If the snapshot information is not available (eg: release pipeline doesn't have labels/annotations yet) then we will not show the snapshot section.

**Review by jeff-phillips-18 — APPROVED** [review]
/lgtm

**Pull request merged**
