### PR TITLE
add loading indicator for component detection

### PR DESCRIPTION
**Pull request by sahil143**
## Description

Add loading indicator for component detection in samples flow

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image
Screenshot 2022-10-03 at 5 22 33 PM
image
image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — APPROVED** [review]
/lgtm

**Comment by rottencandy** [comment]
cc @openshift/team-hacdev-ux

**Comment by Misjohns** [comment]
@sahil143 Can you verify the screencaps are in the correct order? They seem to be out of order. Or post a video?

**Comment by sahil143** [comment]
Kapture 2022-10-06 at 13 59 37

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
@sahil143 Overall the changes looks good but I think we are missing the filter toolbar that is recommended by the new design.

**Comment by Misjohns** [comment]
Can we use this concept instead? Maybe copy could say "Detecting values".
image (11)

**Comment by sahil143** [comment]
Updated screenshot
image

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
