### PR TITLE
support generic task run result for CVE scan results

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [RHTAPBUGS-185](https://issues.redhat.com/browse/RHTAPBUGS-185)
Closes [HAC-3774](https://issues.redhat.com/browse/HAC-3774)

## Description
Adds support to aggregate CVE scan results from any tasks that contain scan results.
Add the vulnerabilities scan info to task run details page when the task contains scan results.

## Type of change
- [x] Feature
- [x] Bugfix

## Screen shots / Gifs for design review 
image

image

/cc @rohitkrai03 @karthikjeeyar @MariaLeonova

### CODE REVIEW

**Comment by MariaLeonova** [comment]
@jeff-phillips-18 do we maybe want to add View logs on a task run? Or is it obvious enough?

**Comment by jeff-phillips-18** [comment]
@MariaLeonova The logs are already available as a tab above. We could add but seems redundant.

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
