### PR TITLE
feat(components): update components list view

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-4533](https://issues.redhat.com/browse/HAC-4533)

## Description
Update the components list view per [DTUX-1619](https://issues.redhat.com/browse/DTUX-1619)

## Type of change
- [x] Feature

## Screen shots / Gifs for design review 

image

/cc @MariaLeonova @Misjohns

### CODE REVIEW

**Comment by beaumorley** [comment]
Hi @jeff-phillips-18 Masha is on PTO until Monday. @Misjohns and I are going to meet tomorrow to go over Ran's design on this. I see this is a WIP but at some point we may need to see this interactive for a review. . Let me know if you have questions in the mean time.

**Comment by jeff-phillips-18** [comment]
> Hi @jeff-phillips-18 Masha is on PTO until Monday. @Misjohns and I are going to meet tomorrow to go over Ran's design on this. I see this is a WIP but at some point we may need to see this interactive for a review. . Let me know if you have questions in the mean time.

Thanks @beaumorley .  This is only WIP due to the dependance on #794 .  The code changes and the UI changes are complete.

**Comment by Misjohns** [comment]
@jeff-phillips-18 UX met this morning to review and here are the changes we'd like incorporated.
- Remove the labels in the **Build pipeline plan** column; these should just be static text.

Can you help us understand the difference between the **Build trigger** and the second row of the **Latest build** columns? It feels like they are redundant. Both include "manual" links. We these linked to different pages?

For the other links, is this correct?
- Human resources (component name) links to the component details view
- jeff-phillips-18/... (url) opens source in the repo (ie. github)
- #18 Update RHTAP references (commit name) links to the commit details view
- f00ea25 (SHA) opens commit in the repo (ie. github)
- View build logs opens the log modal

**Comment by jeff-phillips-18** [comment]
> @jeff-phillips-18 UX met this morning to review and here are the changes we'd like incorporated.
> 
> * Remove the labels in the **Build pipeline plan** column; these should just be static text.

This was following https://docs.google.com/document/d/1wGNAku8Elz6fa4Vy8sD6ARETWTKirgSXVHxQWjLtXoI/edit#heading=h.9oy99xphu2rk. However, we have not yet updated to the microcopy there. These labels are used elsewhere as well and should all be updated together. If you don't want the labels that is fine, currently when clicked they allow the user to edit the plan for that component. That could be removed and users could do it simply from the component details page.

> 
> Can you help us understand the difference between the **Build trigger** and the second row of the **Latest build** columns? It feels like they are redundant. Both include "manual" links. We these linked to different pages?

The build trigger column just shows how the build was triggerd:
image

image

> 
> For the other links, is this correct?
> 
> * Human resources (component name) links to the component details view
> * jeff-phillips-18/... (url) opens source in the repo (ie. github)
> * 18 Update RHTAP references (commit name) links to the commit details view
> * f00ea25 (SHA) opens commit in the repo (ie. github)
> * View build logs opens the log modal

correct on all fronts

**Comment by MariaLeonova** [comment]
@jeff-phillips-18 this looks really good! 
I have a couple questions regarding the card on top:
- is it in any way responsive to the current status?
- what happens when a user clicks on **Edit build pipeline plans** button?
- shall we consider making it a bit more compact? I don't see a need for the card to take half of the real estate. Please see my suggestions:  
image

**Comment by jeff-phillips-18** [comment]
> @jeff-phillips-18 this looks really good! I have a couple questions regarding the card on top:
> 
> * is it in any way responsive to the current status?

No, this is a simple getting started box. It shows until the user closes it then will not show next time the user visits the page.

> * what happens when a user clicks on **Edit build pipeline plans** button?

It brings up the `Manage build pipelines` dialog:

image

> * shall we consider making it a bit more compact? I don't see a need for the card to take half of the real estate. Please see my suggestions:
> 
> image

Sure. Do you have a preference which version?

**Comment by MariaLeonova** [comment]
> Sure. Do you have a preference which version?

I would go for the one with button on the right, if it can be responsive. I.e. the button sticks to the text when the screen is made wider, the button goes under when the screen is smaller than 480 px (?). @Misjohns would that be a good number?

**Comment by MariaLeonova** [comment]
@jeff-phillips-18 on the old list we have a link to view pod logs, where will it be accessible from? Fro the component details?

**Comment by jeff-phillips-18** [comment]
> the button sticks to the text when the screen is made wider, the button goes under when the screen is smaller than 480 px

It would automatically wrap when it doesn't fit.

**Comment by jeff-phillips-18** [comment]
> @jeff-phillips-18 on the old list we have a link to view pod logs, where will it be accessible from? Fro the component details?

@MariaLeonova There is a `View build logs` link to the right in each row that brings up the pod logs modal.

**Comment by MariaLeonova** [comment]
> > @jeff-phillips-18 on the old list we have a link to view pod logs, where will it be accessible from? Fro the component details?
> 
> @MariaLeonova There is a `View build logs` link to the right in each row that brings up the pod logs modal.

Oh so it was just renamed? Okay

**Comment by jeff-phillips-18** [comment]
Updated Getting Started card:
image

**Comment by jeff-phillips-18** [comment]
Removed `WIP` status, ready for final reviews. @MariaLeonova @karthikjeeyar

**Comment by jeff-phillips-18** [comment]
> One thing I would suggest is to bring the title and the text in the acrd closer together, if possible.

@MariaLeonova This is using a PatternFly component so the spacing is standardized.

**Comment by karthikjeeyar** [comment]
Can we have a reserve the space for pipelinerun status as it loads, so that the kebab menu will stay always on right most side?


Screenshot 2023-10-13 at 5 25 05 PM

**Pull request merged**
