### PR TITLE
add filter to Pipeline run list

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-2789

## Description

Adds status and name filter to PLR list

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-01-27 at 5 47 57 PM
Screenshot 2023-01-27 at 5 48 08 PM

## How to test or reproduce?

yet to update tests

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
Screenshot 2023-01-31 at 2 52 52 PM

**Review by karthikjeeyar — APPROVED** [review]
Adding unit tests for the conditional rendering of the content & empty state may help avoid the code coverage check failure and improve the coverage.

**Pull request merged**
