### PR TITLE
add hacbs environments

### PR DESCRIPTION
**Pull request by christianvogt**
## Fixes 
https://issues.redhat.com/browse/HACBS-832

## Description

HACBS:
- adds filter by name and by type (Static, Managed) to the `Settings` -> Environments list
  - filters are stored in the query string
- adds environment type label to the environment cards
- adds Environments list to the Application details Environments Tab
  - shows Static, Managed, and Ephemeral types

_Note: `ephemeral` environments label should be `gold` however the PF version we use doesn't support it._

App studio:
- adds filter by name to the `Settings` -> Environments list

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

**NOTE:** Screens are out of date for `Create Environment` button which is now `Create environment`

hacbs settings page:
image

image

image

image

image

image

hacbs environments tab:
image

image

image

image

image

App Studio settings page:
image

image

image

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by Ranelim** [comment]
@christianvogt LGTM!

@MariaLeonova Anything requires further fixes?

**Comment by christianvogt** [comment]
Working on unit tests and I need to change to read `spec.tags` for the environment types instead of the `spec.type`.

**Comment by MariaLeonova** [comment]
This is great, @christianvogt ! One small issue, that I see, is the upper case `Started` on the very first page. It should say `To get started` (lower case). In the same way `Create Environment` button confuses me - why the upper-case for Environment ? 
@abigaeljamie should we use lower-case for the word `environment` here?

On the same screen: I am guessing, there's no [sidepanel](https://docs.google.com/document/d/18kZkI8fU2e3YwJzLlnBuosDo79rcU3r2aE_hwTBY2QE/edit#bookmark=id.cggxnyphbwdt) a `Learn more` could point to just yet, thus it's not included?

[The Release environment card ](https://docs.google.com/document/d/18kZkI8fU2e3YwJzLlnBuosDo79rcU3r2aE_hwTBY2QE/edit#bookmark=id.tkkr6euczo2s)should also include a workspace link and release strategy info, as well as mention of Enterprise contract and latest release date. Will those be covered in separate PRs?

**Comment by christianvogt** [comment]
@MariaLeonova I'll update the casing for `get Started` and the `Create Environment` button.

There is no `Learn more` because we don't have copy yet to display in the side panel.

The environment cards do not have the full details because they are not yet available.

Future PRs will be added to refine the experience.

**Comment by abigaeljamie** [comment]
> This is great, @christianvogt ! One small issue, that I see, is the upper case `Started` on the very first page. It should say `To get started` (lower case). In the same way `Create Environment` button confuses me - why the upper-case for Environment ? @abigaeljamie should we use lower-case for the word `environment` here?
> 
> On the same screen: I am guessing, there's no [sidepanel](https://docs.google.com/document/d/18kZkI8fU2e3YwJzLlnBuosDo79rcU3r2aE_hwTBY2QE/edit#bookmark=id.cggxnyphbwdt) a `Learn more` could point to just yet, thus it's not included?
> 
> [The Release environment card ](https://docs.google.com/document/d/18kZkI8fU2e3YwJzLlnBuosDo79rcU3r2aE_hwTBY2QE/edit#bookmark=id.tkkr6euczo2s)should also include a workspace link and release strategy info, as well as mention of Enterprise contract and latest release date. Will those be covered in separate PRs?

Yes, that's right @MariaLeonova !

**Comment by abigaeljamie** [comment]
I'm also curious if we can update the empty state to follow the [copy patterns from PatternFly](https://www.patternfly.org/v4/components/empty-state/design-guidelines)? So it would end up like this: 

Heading: No results found 
Body: Adjust your filters and try again.

**Comment by christianvogt** [comment]
@abigaeljamie we can adjust the empty states on the dev side when we get consistency across the design documents and later make a single pass to update several screens at once. fyi @Ranelim @MariaLeonova

**Comment by christianvogt** [comment]
rebased

**Comment by karthikjeeyar** [comment]
image

/lgtm

**Comment by christianvogt** [comment]
rebased and fixed up the e2e tests:

image

**Comment by christianvogt** [comment]
new rebase with several changes to fix up broken URLs from some other PRs that broke e2e

image

**Pull request merged**
