### PR TITLE
UI treatment for displaying Application repositories

### PR DESCRIPTION
**Pull request by christianvogt**
## Fixes 

https://issues.redhat.com/browse/HAC-3580

## Description

Update all UI where we render git repo URLs.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image
image
image
image
image

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by christianvogt** [comment]
rebased PR

**Comment by christianvogt** [comment]
rebased

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
