### PR TITLE
Update empty state image for application list

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-2002

## Description
Update empty state image for application list.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
cc @openshift/team-hacdev-ux

**Review by sahil143 — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by rohitkrai03** [comment]
@rottencandy Can you update e2e test run for this PR?

**Comment by rottencandy** [comment]
E2e passing
screenshot-1660736246

**Pull request merged**
