### PR TITLE
feat(private-auth): add a form to initiate private auth flow

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/HAC-5453

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
If I enter invalid repo and then change to valid repo, looks like the auth section is not removed
Screenshot 2023-11-16 at 22-12-38 Import - Add components Red Hat Trusted Application Pipeline

**Comment by sahil143** [comment]
> If I enter invalid repo and then change to valid repo, looks like the auth section is not removed Screenshot 2023-11-16 at 22-12-38 Import - Add components Red Hat Trusted Application Pipeline

@rottencandy fixed this issue. Please test again.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
