### PR TITLE
update application name validation message

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-3150

## Description

Better validation messaging around app name
Updates to "Must start with a letter and end with a letter or number. Valid characters include lowercase letters from a to z, numbers from 0 to 9, and hyphens ( - )." 

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-03-03 at 5 25 49 PM

Screenshot 2023-03-09 at 5 41 15 PM

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
Should we update the message for component as well? We use the same regex for it and right now it's not very descriptive

**Comment by christianvogt** [comment]
/lgtm cancel

@abhinandan13jan please update the message for component name as well

**Comment by abhinandan13jan** [comment]
updated

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Comment by abhinandan13jan** [comment]
I am adding some tests to better the codecov report

**Pull request merged**
