### PR TITLE
Update review section loading message

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-2624

## Description
Update detecting components message.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

https://user-images.githubusercontent.com/20013884/212109157-8d33d4f8-1f02-4998-bbfc-8126f6041f4a.mp4

## How to test or reproduce?
Add components.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rottencandy** [comment]
cc @openshift/team-hacdev-ux

**Comment by rohitkrai03** [comment]
Hey, I've merged the PR that fixed the e2e tests - #305. So going forward it would be good to run the e2e tests locally and paste the screenshot here on the PR before merging. Can you do that?

**Review by sahil143 — APPROVED** [review]
/lgtm

verified locally

**Review by abigaeljamie — APPROVED** [review]
Thank you for applying the new message! LGTM

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
