### PR TITLE
Show routes as component URL on component cards

### PR DESCRIPTION
**Pull request by rohitkrai03**
## Fixes 

- https://issues.redhat.com/browse/HAC-2787
- https://issues.redhat.com/browse/HAC-2929
- https://issues.redhat.com/browse/HAC-2968

## Description

- Update the component list view to show routes for the component on top of the card.
- Updated component details labels.

## Type of change

- [x] Feature

## Screen shots / Gifs for design review 

Screenshot 2023-01-18 at 10 38 53 PM

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

### CODE REVIEW

**Comment by rohitkrai03** [comment]
E2E test run screenshots --
Screenshot 2023-01-18 at 11 22 15 PM
Screenshot 2023-01-18 at 11 25 32 PM

Screenshot 2023-01-18 at 11 30 32 PM

**Comment by christianvogt** [comment]
@rohitkrai03 if you're going to make changes, can you make some some of the additional to align the text with the UX doc:
image

**Comment by christianvogt** [comment]
@rohitkrai03 in the design docs, the route is no longer displayed in the expanded exception also `Built container image` is changed to `Build Container Image`.
Could you make these final changes.

**Comment by rohitkrai03** [comment]
I confirmed with @beaumorley about having full route in the expanded section and also confirmed that we do not need to change built to build container image.

**Comment by beaumorley** [comment]
@rohitkrai03 I added a note to the top of the design doc to document the comments above. Thank you!

**Comment by beaumorley** [comment]
> @rohitkrai03 in the design docs, the route is no longer displayed in the expanded exception also `Built container image` is changed to `Build Container Image`. Could you make these final changes.

Matt R asked us to keep the copy "Built container image". I made an update in the design doc around this request. (I had thought it was a typo but he says it is not. Will plan to review all of these post MVP.)

Thanks!

**Pull request merged**
