### PR TITLE
Update text to align with UX designs

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-540

## Description

Update text and some layouts to align with UX designs.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by Misjohns** [comment]
There's a but too much space between the "No code?" and "Start with a sample."

**Comment by rottencandy** [comment]
> A few questions and comments:
> 
>     1. What is the Multi Component check box on the first screen? That should be the "Authorize Git repository" section.
>     ...
> 
>     3. Each component on the Review screen should include an icon.

The multi component checkbox is used to denote whether the repository contains multiple components so all of them can be detected. This was not in the designs, but required by the API.
Haven't added authorization fields since API doesn't support it yet, and it will be part of milestone 3.

Not sure what do do about the icons, repositories don't always provide them, and at this point we don't have a way to get the correct icons through the API.

**Comment by rottencandy** [comment]
Updated with rest of the suggestions:

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
/lgtm
/approve

**Review by rohitkrai03 — APPROVED** [review]

**Pull request merged**
