### PR TITLE
applications list view

### PR DESCRIPTION
**Pull request by debsmita1**
## Fixes 
https://issues.redhat.com/browse/HAC-542

## Description
- the Applications list page lists all the applications if available otherwise the empty state is being shown, the most recently deployed application is listed first
- user can create a new app by clicking on the `Create Application` button on the list page
- clicking on the application name will take the user to the Composition view page
- added tests

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Gifs & screenshots for design review 
applistpage
emptystate

## How to test or reproduce?
Goto URL : https://prod.foo.redhat.com:1337/beta/hac/app-studio/applications

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by divyanshiGupta — CHANGES_REQUESTED** [review]

**Comment by divyanshiGupta** [comment]
@debsmita1 `ApplicationListRow.spec.tsx` tests are failing. PTAL.

**Comment by debsmita1** [comment]
> @debsmita1 `ApplicationListRow.spec.tsx` tests are failing. PTAL.

Fixed it ! PTAL

**Review by rottencandy — COMMENTED** [review]
When there are no applications, I see this text and no button. Should we be showing the empty state page with link to create applications?

**Pull request merged**
