### PR TITLE
Use uploadUrl for token upload flow

### PR DESCRIPTION
**Pull request by rottencandy**
## Fixes 
https://issues.redhat.com/browse/HAC-2209

## Description
Use `uploadUrl` for token upload flow instead of using a hardcoded URL.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
(No UI changes)

https://user-images.githubusercontent.com/20013884/192510486-66c34ece-feb5-4438-b596-6a1bba6fd390.mp4

## How to test or reproduce?
Use token upload flow.

## Browser conformance: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Review by sahil143 — APPROVED** [review]
/lgtm

**Pull request merged**
