### PR TITLE
update integration test popover content

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/HAC-3242

## Description

Update popover content for integration test based on the new designs.

## Type of change

- [x] Refactoring (no functional changes, no api changes)

## Screen shots / Gifs for design review 

Screenshot 2023-03-06 at 1 28 44 PM

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

cc: @abhinandan13jan @MariaLeonova

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
@karthikjeeyar There is an `enterprise contract` and `status` in the doc? Is it a future implementation? I dont see it in the screenshot

**Comment by MariaLeonova** [comment]
@abhinandan13jan enterprise contract with a status will appear in the popover once you run it as an integration test on the app. Any other test that has been set up will appear there as well.

**Pull request merged**
