### PR TITLE
Update computation of deployed application status

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [RHTAPBUGS-783](https://issues.redhat.com/browse/RHTAPBUGS-783)

## Description
Update the computation of the deployed application status to use status.gitopsDeployment instead of status.componentsDeploymentConditions

## Type of change
- [x] Bugfix

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by jeff-phillips-18** [comment]
Updated application header to match status show in the cards (though this may be removed soon at least it is consistent until it is removed):

image

**Pull request merged**
