### PR TITLE
Fix mounted files permissions

### PR DESCRIPTION
**Pull request by Katka92**
## Fixes 
https://issues.redhat.com/browse/KFLUXUI-208

## Description
Enable Jenkins to remove the files from node.

### CODE REVIEW

**Comment by caugello** [comment]
@Katka92 does this needs to be merged first to have the build succeeding by CI ?

**Comment by Katka92** [comment]
@caugello The PR check tests are "working". If it keeps failing for you on this error (see below), keep retrying it. Once the node dies, the new node would be able to run the tests again.
```
Wiping out workspace first.
Also:   java.nio.file.FileSystemException: /var/lib/jenkins/workspace/openshift-hac-dev-pr-check/build/container_workspace/integration-tests/.dockerignore: Operation not permitted
```

**Pull request merged**
