### PR TITLE
remove case sensitive filters in the commit list view

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/HAC-2997
https://issues.redhat.com/browse/HAC-3010

## Description

1. "Filter by name"  filter performs a case sensitive search in the commit list view name field rather it should perform case insensitive search.
~2. The name field should display a valid PR number (eg: `#4`) , previously it was showing `# undefined`  string.~ (fixed already in another PR, so reverted the change)

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

**Filter by name:** 

Screenshot 2023-01-23 at 1 55 11 PM

https://user-images.githubusercontent.com/9964343/214000314-2c0e3524-9609-4957-84f5-eaa2512f81f7.mov

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

https://user-images.githubusercontent.com/9964343/214000375-e3d9b094-77a3-424e-ae14-ef18981dae2b.mov

### CODE REVIEW

**Comment by sahil143** [comment]
@karthikjeeyar PR number(undefined) should be fixed in https://github.com/openshift/hac-dev/pull/349.

**Comment by karthikjeeyar** [comment]
Thanks @sahil143, I reverted that change and rebased the code.

**Review by sahil143 — COMMENTED** [review]
@karthikjeeyar I think we should include the PR number in title while filtering.

image
image

**Comment by karthikjeeyar** [comment]
@sahil143 I have fixed it.

**Review by sahil143 — APPROVED** [review]
/lgtm

verified locally

**Pull request merged**
