### PR TITLE
add breadcrumb for component

### PR DESCRIPTION
**Pull request by abhinandan13jan**
## Fixes 

https://issues.redhat.com/browse/HAC-2336

## Description

Adds breadcrumbs for component name.

## Type of change

- [ ] Feature
- [x] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

Screenshot 2023-01-04 at 5 50 59 PM

Screenshot 2022-12-28 at 5 49 04 PM

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by christianvogt** [comment]
The breadcrumb and the name don't match as the component name contains hyphens. Elsewhere in the UI we also show the resource name and not a cleaned up display name.

I think we should be consistent and show the same value everywhere.
@MariaLeonova thoughts?

**Comment by MariaLeonova** [comment]
@christianvogt I agree: since we decided to have resource names throughout , we should show it in the breadcrumb as well.

**Comment by karthikjeeyar** [comment]
@abhinandan13jan Please update the PR with above changes

/lgtm cancel

**Comment by karthikjeeyar** [comment]
@christianvogt @MariaLeonova Correct me if I am wrong, I think the suggested changes should be applied for component's name but not for the application name as we are using display name for application in the details page. 

Application name in this breadcrumb doesn't match with display name in Application details page and its breadcrumb.

image


https://user-images.githubusercontent.com/9964343/210544439-eef05b3c-1063-45e8-ba0d-7191097b9202.mov

**Comment by MariaLeonova** [comment]
@karthikjeeyar you're right, and this takes us back to the do we need a display name for apps discussion. Here's what we discussed in the stakeholder call in November: https://docs.google.com/document/d/1BvQoEU_OL6Ei1Ly0-dx5kzx-FyKE5YuiiFbZ0cBTFLk/edit?disco=AAAAjVEmcV8

**Comment by abhinandan13jan** [comment]
> @christianvogt I agree: since we decided to have resource names throughout , we should show it in the breadcrumb as well.

@karthikjeeyar @MariaLeonova My bad, when you said resource names throughout, I assumed you meant application too. I've updated
Screenshot 2023-01-04 at 5 50 59 PM

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
