### PR TITLE
add `Detecting runtime` message instead of spinner

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/HAC-2909

## Description

Replace the runtime detection spinner with disabled dropdown with `Detecting runtime...` message.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

**Detecting phase screenshot:**

detecting_spinner

**Detection full video:**

detecting_runtime_spinner

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

/cc @christianvogt

### CODE REVIEW

**Comment by Misjohns** [comment]
@karthikjeeyar Can we include a small spinner infront of the "Detecting runtime" inside the dropdown? Similar to https://www.patternfly.org/v4/components/button/html-demos/#progress-button---loading

**Comment by karthikjeeyar** [comment]
Thanks @Misjohns for review, I have added the spinner and updated the screenshots in the PR description. PTAL

**Pull request merged**
