### PR TITLE
add application deployment status to details page

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/HAC-2623

## Description

add application deployment status to details page

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rohitkrai03** [comment]
@sahil143 Unit tests are failing for the PR. Can you check?

**Comment by sahil143** [comment]
> @sahil143 Unit tests are failing for the PR. Can you check?

should be fixed now.

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
