### PR TITLE
update all empty state copy / icons

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-2837](https://issues.redhat.com/browse/HAC-2837)

## Description
Updates all copy and icons for all empty states per https://docs.google.com/document/d/1ouUwFdxl0f4j0sO5Zi1JwQZvnk2JhzNhwVkOo_JqxbY

Removed the unused old version of the Application details view in order to more easily adjust the empty state for the view.

## Type of change
- [x] Feature

## Screen shots / Gifs for design review 
image

image

image

image

image

image

### CODE REVIEW

**Comment by Misjohns** [comment]
@jeff-phillips-18 Maybe you are still working to update the microcopy but the images above don't include the updated copy. Also, we need to add some space to the top and bottom of the message. Let's use 48px padding from the top of the dotted container and the top of the icon and 48px padding from the bottom of the buttons and the dotted container.

**Comment by jeff-phillips-18** [comment]
> Let's use 48px padding from the top of the dotted container and the top of the icon and 48px padding from the bottom of the buttons and the dotted container.

@Misjohns We can, but currently this is using standard PatternFly spacing.

**Comment by jeff-phillips-18** [comment]
@Misjohns Updated and updated the images above.

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
I am using SVGs provided by UX in this https://github.com/openshift/hac-dev/pull/371 instead of pngs. I think it would be better to use SVGs. What do you think?

**Comment by jeff-phillips-18** [comment]
> I am using SVGs provided by UX in this #371 instead of pngs. I think it would be better to use SVGs. What do you think?

SVGs are preferable. Do we have SVGs for these icons?

**Comment by jeff-phillips-18** [comment]
Updated to use SVGs

**Comment by jeff-phillips-18** [comment]
@Misjohns Can you please take another look and comment?

**Comment by christianvogt** [comment]
Looks like the pipeline runs filter list wasn't update with the new icon:

image

**Comment by christianvogt** [comment]
Other than the above, it seems everything else is in order.

/approve

**Comment by christianvogt** [comment]
Also the samples page could use a new icon:
image

**Comment by jeff-phillips-18** [comment]
Updated the remain empty states

**Pull request merged**
