### PR TITLE
Add ability to add an integration test to an application

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HACBS-820](https://issues.redhat.com/browse/HACBS-820)

## Description
Allows users to add an integration test to an existing application, either from the empty state or from the actions menu for an application.

## Type of change
- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 
image

image

## How to test or reproduce?

Navigate to an Application.
From the `Actions` menu, select `Add integration test`

Navigate to an application that has no integration tests.
Click the `Add integration test` button.

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Comment by Ranelim** [comment]
@jeff-phillips-18  Looks good to me, thank you!

I believe we don't have that external doc ready, the one within the page description.
Perhaps it is better to remove it until were do

**Comment by jeff-phillips-18** [comment]
> I believe we don't have that external doc ready, the one within the page description.
> Perhaps it is better to remove it until were do

@Ranelim I did not add that link, but I can remove it if we don't want it yet.

**Comment by christianvogt** [comment]
/approve
Designs have the save button read `Add integration test pipeline`.

**Comment by jeff-phillips-18** [comment]
@christianvogt Updated the submit button:

image

**Pull request merged**
