### PR TITLE
feat(STONEINTG-974): keep ITS contexts field when editing

### PR DESCRIPTION
**Pull request by dirgim**
* Since users can manually modify the .spec.contexts field of their integrationTestScenario, the edit page should not overwrite it with the default data
* See more in [STONEINTG-974](https://issues.redhat.com/browse/STONEINTG-974)

Signed-off-by: dirgim <kpavic@redhat.com>

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by Katka92** [comment]
[test]

**Comment by sahil143** [comment]
[test]

**Review by sahil143 — APPROVED** [review]
/lgtm

**Comment by dirgim** [comment]
[test]

**Review by rohitkrai03 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
