### PR TITLE
Show commits for manual/default build pipelines

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Fixes 
Fixes [HAC-3712](https://issues.redhat.com/browse/HAC-3712)

## Description
Show commits from manual/default build pipelines. Not all fields are available but show the fields that are.

## Type of change
- [x] Feature

## Screen shots / Gifs for design review 
image (1)

image (2)

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
overall commit status (badge & status field)  and static environment node status are stuck in `Pending` state. This could be due to some of the API calls still uses pac based label selectors while fetching objects.

image

**Comment by jeff-phillips-18** [comment]
@rohitkrai03 Please take another look:

image


image

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
