### PR TITLE
Integration test Tab Edit test scenarios.

### PR DESCRIPTION
**Pull request by subhashkhileri**
## Fixes 

Integration test Tab Edit test scenarios.
https://issues.redhat.com/browse/HACBS-1462

## Description

Reach the "Edit integration test" page by:

1. Go to an IT's Details page and click on the "Edit integration test" option under the "Actions" dropdown.
2. Go to IT list view, and click on the "Edit" option under IT's kebab menu.

Then test the Edit form by making sure that:

- `Integration test name` input is marked as read-only and cannot be edited.
- `Save changes` button only gets enabled if the edit form has new changes.
- update the `pipelineName` and `Mark Optional For Release` 
- Verify that the latest changes are reflected on the IT list and detail view.  

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): Test Case

## Browser conformance: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rohitkrai03** [comment]
@subhashkhileri We don't have the integration test tab or the action item in the UI anymore. How are you testing it?

**Comment by subhashkhileri** [comment]
@rohitkrai03 I have tested with MVP_FLAG false in my local, and these tests are skipped so will not run in PR check.

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
