### PR TITLE
add Context Switcher to Application details view

### PR DESCRIPTION
**Pull request by sahil143**
## Fixes 

https://issues.redhat.com/browse/HAC-2622

## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Screen shots / Gifs for design review 

image

## Browser conformance: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
If I click on already selected application, the params are removed.
Maybe we can avoid running callback if a key is already selected?

https://user-images.githubusercontent.com/20013884/208612246-e5c8b698-2a5c-4a26-85fc-cc7801419f2c.mp4

**Comment by sahil143** [comment]
> If I click on already selected application, the params are removed.
Maybe we can avoid running callback if a key is already selected?

@rottencandy fixed!

**Review by rottencandy — APPROVED** [review]
/lgtm

**Comment by rohitkrai03** [comment]
@sahil143 You've got some conflicts after merging your other PR.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
