### PR TITLE
add integration test link in test pipelinerun details page

### PR DESCRIPTION
**Pull request by karthikjeeyar**
## Fixes 

https://issues.redhat.com/browse/RHTAPBUGS-480

## Description

Adds link back to the Integration test object thats is defines this test pipelinerun.

## Type of change

- [x] Bugfix

## Screen shots / Gifs for design review 

image

## How to test or reproduce?

 Visit test pipelinerun details page to see the link of the Integration test object.

## Browser conformance: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
cc: @MariaLeonova

**Comment by MariaLeonova** [comment]
@karthikjeeyar looks good to me! I think this should work just fine.

**Pull request merged**
